# Generated by Django 2.2 on 2020-03-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MpesaCallsa',
            new_name='MpesaCalls',
        ),
    ]
